### ISSUE TITLE
Drupal included?

### ISSUE THREAD

**Issue by osadi** [dnmgns/localdev.ninja#10]
Is Drupal still included? According to README it is.

```
It's also possible to create a drupal installation by uncommenting #include drupal in ./puppet/manifests/base.pp. Make sure that you set your drupal installation variables by editing ./puppet/modules/drupal/manifests/variables.pp.
```

**Comment by dnmgns** [comment]
Drupal has been removed. It was a auto-provision-drupal thingy which created a new project, with database etc...

**Comment by dnmgns** [comment]
If you want to try it out, checkout commit 4a3542f29d0facfe93e04aaec69f60c2038a6ede
